name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make 3dsx
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: |
          Touch-Keys.3dsx
